depends_on:
  - lint
  - build
  - test

steps:
  build:
    image: debian:stable-slim
    commands:
      - echo "* Deploying code..."
      - sleep 2
      - echo "done"
      - sleep 2

#https://woodpecker-ci.org/plugins/Ansible
