# --backend-engine auto-detect | WOODPECKER_BACKEND=auto-detect
steps:
  build:
    image: debian:stable-slim
    commands:
      - echo "hello"
      - sleep 2
      - echo "world"
      - sleep 2
      - echo "done"
      - sleep 2
