steps:
  build:
    image: debian:stable-slim
    commands:
      - sleep 1
      - true

when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - release/*
